### ISSUE TITLE
Ask for help！

### ISSUE THREAD

**Issue by GodXYZ2** [NSS-01/Basalt-Federated-learning#1]
Hello, I would like to ask if this paper of yours has been published. If not, I would like to quote this code and how to quote it. I would be grateful if you could take time out of your busy schedule to answer me.

**Comment by NSS-01** [comment]
Our paper is under review in ITFS.  I will take a look at the publishing requirements of TIFS and see if it is possible to publish it on Techrxiv.  In the following week, we will provide a citation.

**Comment by GodXYZ2** [comment]
That would be great. Thank you very much！

**Comment by NSS-01** [comment]
@article{Song_2024,
title={Basalt: Server-Client Joint Defense Mechanism for Byzantine-Robust Federated Learning},
url={http://dx.doi.org/10.36227/techrxiv.171073035.50327931/v1},
DOI={10.36227/techrxiv.171073035.50327931/v1},
publisher={Institute of Electrical and Electronics Engineers (IEEE)},
author={Song, Anxiao and Li, Haoshuo and Zhang, Tao and Cheng, Ke and Shen, Yulong},
year={2024},
month=mar }
